name: Publish Docker Image on Release
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get tag name
        id: tag_name
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ${{ format('kbruen/awesome-demo-app-server:{0}', steps.tag_name.outputs.TAG) }}
          push: true

